name:                css-parser
version:             0.1.0.0
github:              "gege251/css-parser"
license:             BSD3
author:              "Szabo Gergely"
maintainer:          "gege251@gmail.com"
copyright:           "2018 Szabo Gergely"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/css-parser#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13.2.2 && < 0.14
- text

library:
  source-dirs: src

executables:
  css-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - css-parser

tests:
  css-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - css-parser
    - hspec
    - hspec-attoparsec
